name: steam_login
description: Library to authenticate users with Steam OpenID and functions to call steam WebAPI.
version: 1.0.3
homepage: https://github.com/Hexer10/steam_login
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0